import Post from "public/class/Post";
import testPostImg from "public/img/testImg.jpg";
import testPostImg2 from "public/img/dummy/meta_mong.jpg";

export const dummyPosts: Post[] = [
  new Post("1페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
  new Post("1페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [], 4, 3),
  new Post("1페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
  new Post("1페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [], 4, 3),
  new Post("1페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 0, 0),
  new Post("1페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
  new Post("1페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [], 4, 3),
  new Post("1페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 123, 48),
  new Post("1페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg]),
  new Post("1페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),

  new Post("2페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg2], 4, 3),
  new Post("2페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg2], 4, 3),
  new Post("2페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg2], 4, 3),
  new Post("2페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg2], 4, 3),
  new Post("2페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg2], 4, 3),
  new Post("2페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg2], 4, 3),
  new Post("2페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg2], 4, 3),
  new Post("2페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg2], 4, 3),
  new Post("2페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg2], 4, 3),
  new Post("2페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg2], 4, 3),

  new Post("3페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
  new Post("3페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
  new Post("3페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
  new Post("3페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
  new Post("3페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
  new Post("3페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
  new Post("3페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
  new Post("3페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
  new Post("3페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
  new Post("3페이지 제목", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, accusamus labore fuga, ipsam vitae excepturi cumque quasi magnam velit ipsum quis vero quam reprehenderit in quibusdam error sunt sint odit?", "자유게시판", "익명", [testPostImg], 4, 3),
];
